#!/bin/bash
#
# Generates the TealPkg release tarball for the current version.
#
# Copyright 2021-2022 Coastal Carolina University
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the “Software”), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED “AS IS”, WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

tempdir=$(mktemp -d)
VERSION=$(cd src && python3 -c 'import tealpkg; print(tealpkg.VERSION)')

mkdir -p "${tempdir}/tealpkg-${VERSION}/src/tealpkg/command"
for item in $(find src -type f -not -path '*/__pycache__/*'); do
    cp "${item}" "${tempdir}/tealpkg-${VERSION}/${item}"
done

cp -r LICENSE README.md conf doc man slack-desc update_slackware_mirrors "${tempdir}/tealpkg-${VERSION}/"
./update_slackware_mirrors > "${tempdir}/tealpkg-${VERSION}/doc/repos/slackware.mirrors"
cat tealpkg.SlackBuild | sed "s/@VERSION@/${VERSION}/" > "${tempdir}/tealpkg-${VERSION}/tealpkg.SlackBuild"

(cd "${tempdir}" && tar cvJf "tealpkg-${VERSION}.tar.xz" "tealpkg-${VERSION}/")

mv "${tempdir}/tealpkg-${VERSION}.tar.xz" "/tmp/tealpkg-${VERSION}.tar.xz"
echo "Source release is at /tmp/tealpkg-${VERSION}.tar.xz"

echo -n "MD5 sum is: "
md5sum "/tmp/tealpkg-${VERSION}.tar.xz" | awk '{print $1}'

[[ "${tempdir}" != "/" ]] && rm -rf "${tempdir}"
